@baseUrl = http://localhost:3001
#@baseUrl = https://part3-caiv.onrender.com
###Get all blogs
GET {{baseUrl}}/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24iLCJpZCI6IjY2YzhmMTU5MmI3MGU2ZTY2OTMxNTljMiIsImlhdCI6MTcyNDQ1MTYxNH0.EJaMHctTKQZZWZxZdBQPvYV6ul2teIMfYwM5hk7Ewkc



@id = 66bbd2a6a231bf96fe4eed7a
###Get a specific person
GET {{baseUrl}}/api/blogs/{{id}}



###Delete a specific person
DELETE {{baseUrl}}/api/blogs/{{id}}



###Create a new blog
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
  "title": "Google Blogs",
  "author": "Google",
  "url": "https://blog.google/products/search/",
  "likes": 80
}



###Update
PUT {{baseUrl}}/api/blogs/{{id}}
Content-Type: application/json

{
  "title": "Stack Overflow",
  "author": "Stack Community",
  "url": "https://stackoverflow.blog/",
  "likes": 90
}



@baseUrl = http://localhost:3001
#@baseUrl = https://part3-caiv.onrender.com
###Get all users
GET {{baseUrl}}/api/users/



###Create a new person
POST {{baseUrl}}/api/users
Content-Type: application/json

{
      "username": "admin",
      "name": "admin",
      "password" : "admin"
}



###Login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
      "username": "tester",
      "password" : "tester"
}



###Create a new blog - with logged in user
POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24iLCJpZCI6IjY2YzhmMTU5MmI3MGU2ZTY2OTMxNTljMiIsImlhdCI6MTcyNDQ1MTYxNH0.EJaMHctTKQZZWZxZdBQPvYV6ul2teIMfYwM5hk7Ewkc

{
  "title": "Leon Blogs4",
  "author": "Leon",
  "url": "https://testblogs.com//",
  "likes": 1000
}



###Get all blogs
GET {{baseUrl}}/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24iLCJpZCI6IjY2YzhmMTU5MmI3MGU2ZTY2OTMxNTljMiIsImlhdCI6MTcyNDQ1MTYxNH0.EJaMHctTKQZZWZxZdBQPvYV6ul2teIMfYwM5hk7Ewkc



@id = 66c92913099d68c6a6594311
###Delete a specific blog
DELETE {{baseUrl}}/api/blogs/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY2YzkwN2ZiYWU0MzQ5YjhlOTllMmFjZiIsImlhdCI6MTcyNDQ1OTMwN30.L-NI2_WxBOY-FLd_-GVZXZygC_YYWLVxxtmSgTk-WJc


###Get all users
GET {{baseUrl}}/api/users/